FROM python:slim

RUN apt-get update && apt-get install -y libgomp1

WORKDIR /app


COPY requirements.txt requirements.txt

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn" ,"main:app", "--host=0.0.0.0"]